#!/bin/sh
rm $1/usr/lib/python2.7/xml/dom/expatbuilder.py*
rm $1/usr/lib/python2.7/__phello__.foo.py*
rm $1/usr/lib/python2.7/_LWPCookieJar.py*
rm $1/usr/lib/python2.7/_MozillaCookieJar.py*
rm $1/usr/lib/python2.7/_pyio.py*
rm $1/usr/lib/python2.7/_strptime.py*
rm $1/usr/lib/python2.7/_threading_local.py*
rm $1/usr/lib/python2.7/aifc.py*
rm $1/usr/lib/python2.7/antigravity.py*
rm $1/usr/lib/python2.7/anydbm.py*
rm $1/usr/lib/python2.7/ast.py*
rm $1/usr/lib/python2.7/asynchat.py*
rm $1/usr/lib/python2.7/asyncore.py*
rm $1/usr/lib/python2.7/audiodev.py*
rm $1/usr/lib/python2.7/Bastion.py*
rm $1/usr/lib/python2.7/bdb.py*
rm $1/usr/lib/python2.7/binhex.py*
rm $1/usr/lib/python2.7/bsddb/__init__.py*
rm $1/usr/lib/python2.7/bsddb/db.py*
rm $1/usr/lib/python2.7/bsddb/dbobj.py*
rm $1/usr/lib/python2.7/bsddb/dbrecio.py*
rm $1/usr/lib/python2.7/bsddb/dbshelve.py*
rm $1/usr/lib/python2.7/bsddb/dbtables.py*
rm $1/usr/lib/python2.7/bsddb/dbutils.py*
rm $1/usr/lib/python2.7/calendar.py*
rm $1/usr/lib/python2.7/cgi.py*
rm $1/usr/lib/python2.7/CGIHTTPServer.py*
rm $1/usr/lib/python2.7/cgitb.py*
rm $1/usr/lib/python2.7/chunk.py*
rm $1/usr/lib/python2.7/cmd.py*
rm $1/usr/lib/python2.7/code.py*
rm $1/usr/lib/python2.7/codeop.py*
rm $1/usr/lib/python2.7/colorsys.py*
rm $1/usr/lib/python2.7/commands.py*
rm $1/usr/lib/python2.7/compileall.py*
rm $1/usr/lib/python2.7/compiler/__init__.py*
rm $1/usr/lib/python2.7/compiler/ast.py*
rm $1/usr/lib/python2.7/compiler/consts.py*
rm $1/usr/lib/python2.7/compiler/future.py*
rm $1/usr/lib/python2.7/compiler/misc.py*
rm $1/usr/lib/python2.7/compiler/pyassem.py*
rm $1/usr/lib/python2.7/compiler/pycodegen.py*
rm $1/usr/lib/python2.7/compiler/symbols.py*
rm $1/usr/lib/python2.7/compiler/syntax.py*
rm $1/usr/lib/python2.7/compiler/transformer.py*
rm $1/usr/lib/python2.7/compiler/visitor.py*
rm $1/usr/lib/python2.7/Cookie.py*
rm $1/usr/lib/python2.7/cookielib.py*
rm $1/usr/lib/python2.7/cProfile.py*
rm $1/usr/lib/python2.7/csv.py*
rm $1/usr/lib/python2.7/ctypes/macholib/__init__.py*
rm $1/usr/lib/python2.7/ctypes/macholib/dyld.py*
rm $1/usr/lib/python2.7/ctypes/macholib/dylib.py*
rm $1/usr/lib/python2.7/ctypes/macholib/framework.py*
rm $1/usr/lib/python2.7/ctypes/wintypes.py*
rm $1/usr/lib/python2.7/curses/__init__.py*
rm $1/usr/lib/python2.7/curses/ascii.py*
rm $1/usr/lib/python2.7/curses/has_key.py*
rm $1/usr/lib/python2.7/curses/panel.py*
rm $1/usr/lib/python2.7/curses/textpad.py*
rm $1/usr/lib/python2.7/curses/wrapper.py*
rm $1/usr/lib/python2.7/dbhash.py*
rm $1/usr/lib/python2.7/decimal.py*
rm $1/usr/lib/python2.7/difflib.py*
rm $1/usr/lib/python2.7/dircache.py*
#rm $1/usr/lib/python2.7/dis.py*
rm $1/usr/lib/python2.7/distutils/archive_util.py*
rm $1/usr/lib/python2.7/distutils/bcppcompiler.py*
rm $1/usr/lib/python2.7/distutils/ccompiler.py*
rm $1/usr/lib/python2.7/distutils/cmd.py*
rm $1/usr/lib/python2.7/distutils/command/__init__.py*
rm $1/usr/lib/python2.7/distutils/command/bdist_dumb.py*
rm $1/usr/lib/python2.7/distutils/command/bdist_msi.py*
rm $1/usr/lib/python2.7/distutils/command/bdist_rpm.py*
rm $1/usr/lib/python2.7/distutils/command/bdist_wininst.py*
rm $1/usr/lib/python2.7/distutils/command/bdist.py*
rm $1/usr/lib/python2.7/distutils/command/build_clib.py*
rm $1/usr/lib/python2.7/distutils/command/build_ext.py*
rm $1/usr/lib/python2.7/distutils/command/build_py.py*
rm $1/usr/lib/python2.7/distutils/command/build_scripts.py*
rm $1/usr/lib/python2.7/distutils/command/build.py*
rm $1/usr/lib/python2.7/distutils/command/check.py*
rm $1/usr/lib/python2.7/distutils/command/clean.py*
rm $1/usr/lib/python2.7/distutils/command/config.py*
rm $1/usr/lib/python2.7/distutils/command/install_data.py*
rm $1/usr/lib/python2.7/distutils/command/install_egg_info.py*
rm $1/usr/lib/python2.7/distutils/command/install_headers.py*
rm $1/usr/lib/python2.7/distutils/command/install_lib.py*
rm $1/usr/lib/python2.7/distutils/command/install_scripts.py*
rm $1/usr/lib/python2.7/distutils/command/install.py*
rm $1/usr/lib/python2.7/distutils/command/register.py*
rm $1/usr/lib/python2.7/distutils/command/sdist.py*
rm $1/usr/lib/python2.7/distutils/command/upload.py*
rm $1/usr/lib/python2.7/distutils/config.py*
rm $1/usr/lib/python2.7/distutils/core.py*
rm $1/usr/lib/python2.7/distutils/cygwinccompiler.py*
rm $1/usr/lib/python2.7/distutils/debug.py*
rm $1/usr/lib/python2.7/distutils/dir_util.py*
rm $1/usr/lib/python2.7/distutils/dist.py*
rm $1/usr/lib/python2.7/distutils/emxccompiler.py*
rm $1/usr/lib/python2.7/distutils/extension.py*
rm $1/usr/lib/python2.7/distutils/fancy_getopt.py*
rm $1/usr/lib/python2.7/distutils/file_util.py*
rm $1/usr/lib/python2.7/distutils/filelist.py*
rm $1/usr/lib/python2.7/distutils/msvc9compiler.py*
rm $1/usr/lib/python2.7/distutils/msvccompiler.py*
rm $1/usr/lib/python2.7/distutils/sysconfig.py*
rm $1/usr/lib/python2.7/distutils/text_file.py*
rm $1/usr/lib/python2.7/distutils/unixccompiler.py*
rm $1/usr/lib/python2.7/distutils/versionpredicate.py*
rm $1/usr/lib/python2.7/doctest.py*
rm $1/usr/lib/python2.7/DocXMLRPCServer.py*
rm $1/usr/lib/python2.7/dumbdbm.py*
rm $1/usr/lib/python2.7/dummy_thread.py*
rm $1/usr/lib/python2.7/dummy_threading.py*
rm $1/usr/lib/python2.7/email/__init__.py*
rm $1/usr/lib/python2.7/email/_parseaddr.py*
rm $1/usr/lib/python2.7/email/base64mime.py*
rm $1/usr/lib/python2.7/email/charset.py*
rm $1/usr/lib/python2.7/email/encoders.py*
rm $1/usr/lib/python2.7/email/errors.py*
rm $1/usr/lib/python2.7/email/feedparser.py*
rm $1/usr/lib/python2.7/email/generator.py*
rm $1/usr/lib/python2.7/email/header.py*
rm $1/usr/lib/python2.7/email/iterators.py*
rm $1/usr/lib/python2.7/email/message.py*
rm $1/usr/lib/python2.7/email/mime/__init__.py*
rm $1/usr/lib/python2.7/email/mime/application.py*
rm $1/usr/lib/python2.7/email/mime/audio.py*
rm $1/usr/lib/python2.7/email/mime/base.py*
rm $1/usr/lib/python2.7/email/mime/image.py*
rm $1/usr/lib/python2.7/email/mime/message.py*
rm $1/usr/lib/python2.7/email/mime/multipart.py*
rm $1/usr/lib/python2.7/email/mime/nonmultipart.py*
rm $1/usr/lib/python2.7/email/mime/text.py*
rm $1/usr/lib/python2.7/email/parser.py*
rm $1/usr/lib/python2.7/email/quoprimime.py*
rm $1/usr/lib/python2.7/email/utils.py*
rm $1/usr/lib/python2.7/encodings/base64_codec.py*
rm $1/usr/lib/python2.7/encodings/big5.py*
rm $1/usr/lib/python2.7/encodings/big5hkscs.py*
rm $1/usr/lib/python2.7/encodings/bz2_codec.py*
rm $1/usr/lib/python2.7/encodings/charmap.py*
rm $1/usr/lib/python2.7/encodings/cp037.py*
rm $1/usr/lib/python2.7/encodings/cp1006.py*
rm $1/usr/lib/python2.7/encodings/cp1026.py*
rm $1/usr/lib/python2.7/encodings/cp1140.py*
rm $1/usr/lib/python2.7/encodings/cp1250.py*
rm $1/usr/lib/python2.7/encodings/cp1251.py*
rm $1/usr/lib/python2.7/encodings/cp1252.py*
rm $1/usr/lib/python2.7/encodings/cp1253.py*
rm $1/usr/lib/python2.7/encodings/cp1254.py*
rm $1/usr/lib/python2.7/encodings/cp1255.py*
rm $1/usr/lib/python2.7/encodings/cp1256.py*
rm $1/usr/lib/python2.7/encodings/cp1257.py*
rm $1/usr/lib/python2.7/encodings/cp1258.py*
rm $1/usr/lib/python2.7/encodings/cp424.py*
rm $1/usr/lib/python2.7/encodings/cp437.py*
rm $1/usr/lib/python2.7/encodings/cp500.py*
rm $1/usr/lib/python2.7/encodings/cp720.py*
rm $1/usr/lib/python2.7/encodings/cp737.py*
rm $1/usr/lib/python2.7/encodings/cp775.py*
rm $1/usr/lib/python2.7/encodings/cp850.py*
rm $1/usr/lib/python2.7/encodings/cp852.py*
rm $1/usr/lib/python2.7/encodings/cp855.py*
rm $1/usr/lib/python2.7/encodings/cp856.py*
rm $1/usr/lib/python2.7/encodings/cp857.py*
rm $1/usr/lib/python2.7/encodings/cp858.py*
rm $1/usr/lib/python2.7/encodings/cp860.py*
rm $1/usr/lib/python2.7/encodings/cp861.py*
rm $1/usr/lib/python2.7/encodings/cp862.py*
rm $1/usr/lib/python2.7/encodings/cp863.py*
rm $1/usr/lib/python2.7/encodings/cp864.py*
rm $1/usr/lib/python2.7/encodings/cp865.py*
rm $1/usr/lib/python2.7/encodings/cp866.py*
rm $1/usr/lib/python2.7/encodings/cp869.py*
rm $1/usr/lib/python2.7/encodings/cp874.py*
rm $1/usr/lib/python2.7/encodings/cp875.py*
rm $1/usr/lib/python2.7/encodings/cp932.py*
rm $1/usr/lib/python2.7/encodings/cp949.py*
rm $1/usr/lib/python2.7/encodings/cp950.py*
rm $1/usr/lib/python2.7/encodings/euc_jis_2004.py*
rm $1/usr/lib/python2.7/encodings/euc_jisx0213.py*
rm $1/usr/lib/python2.7/encodings/euc_jp.py*
rm $1/usr/lib/python2.7/encodings/euc_kr.py*
rm $1/usr/lib/python2.7/encodings/gb18030.py*
rm $1/usr/lib/python2.7/encodings/gb2312.py*
rm $1/usr/lib/python2.7/encodings/gbk.py*
rm $1/usr/lib/python2.7/encodings/hp_roman8.py*
rm $1/usr/lib/python2.7/encodings/hz.py*
#rm $1/usr/lib/python2.7/encodings/idna.py*
rm $1/usr/lib/python2.7/encodings/iso2022_jp_1.py*
rm $1/usr/lib/python2.7/encodings/iso2022_jp_2.py*
rm $1/usr/lib/python2.7/encodings/iso2022_jp_2004.py*
rm $1/usr/lib/python2.7/encodings/iso2022_jp_3.py*
rm $1/usr/lib/python2.7/encodings/iso2022_jp_ext.py*
rm $1/usr/lib/python2.7/encodings/iso2022_jp.py*
rm $1/usr/lib/python2.7/encodings/iso2022_kr.py*
rm $1/usr/lib/python2.7/encodings/iso8859_1.py*
rm $1/usr/lib/python2.7/encodings/iso8859_10.py*
rm $1/usr/lib/python2.7/encodings/iso8859_11.py*
rm $1/usr/lib/python2.7/encodings/iso8859_13.py*
rm $1/usr/lib/python2.7/encodings/iso8859_14.py*
rm $1/usr/lib/python2.7/encodings/iso8859_15.py*
rm $1/usr/lib/python2.7/encodings/iso8859_16.py*
rm $1/usr/lib/python2.7/encodings/iso8859_2.py*
rm $1/usr/lib/python2.7/encodings/iso8859_3.py*
rm $1/usr/lib/python2.7/encodings/iso8859_4.py*
rm $1/usr/lib/python2.7/encodings/iso8859_5.py*
rm $1/usr/lib/python2.7/encodings/iso8859_6.py*
rm $1/usr/lib/python2.7/encodings/iso8859_7.py*
rm $1/usr/lib/python2.7/encodings/iso8859_8.py*
rm $1/usr/lib/python2.7/encodings/iso8859_9.py*
rm $1/usr/lib/python2.7/encodings/johab.py*
rm $1/usr/lib/python2.7/encodings/koi8_r.py*
rm $1/usr/lib/python2.7/encodings/koi8_u.py*
rm $1/usr/lib/python2.7/encodings/latin_1.py*
rm $1/usr/lib/python2.7/encodings/mac_arabic.py*
rm $1/usr/lib/python2.7/encodings/mac_centeuro.py*
rm $1/usr/lib/python2.7/encodings/mac_croatian.py*
rm $1/usr/lib/python2.7/encodings/mac_cyrillic.py*
rm $1/usr/lib/python2.7/encodings/mac_farsi.py*
rm $1/usr/lib/python2.7/encodings/mac_greek.py*
rm $1/usr/lib/python2.7/encodings/mac_iceland.py*
rm $1/usr/lib/python2.7/encodings/mac_latin2.py*
rm $1/usr/lib/python2.7/encodings/mac_roman.py*
rm $1/usr/lib/python2.7/encodings/mac_romanian.py*
rm $1/usr/lib/python2.7/encodings/mac_turkish.py*
rm $1/usr/lib/python2.7/encodings/mbcs.py*
rm $1/usr/lib/python2.7/encodings/palmos.py*
rm $1/usr/lib/python2.7/encodings/ptcp154.py*
rm $1/usr/lib/python2.7/encodings/punycode.py*
rm $1/usr/lib/python2.7/encodings/quopri_codec.py*
rm $1/usr/lib/python2.7/encodings/raw_unicode_escape.py*
rm $1/usr/lib/python2.7/encodings/rot_13.py*
rm $1/usr/lib/python2.7/encodings/shift_jis_2004.py*
rm $1/usr/lib/python2.7/encodings/shift_jis.py*
rm $1/usr/lib/python2.7/encodings/shift_jisx0213.py*
rm $1/usr/lib/python2.7/encodings/tis_620.py*
rm $1/usr/lib/python2.7/encodings/undefined.py*
rm $1/usr/lib/python2.7/encodings/unicode_escape.py*
rm $1/usr/lib/python2.7/encodings/unicode_internal.py*
rm $1/usr/lib/python2.7/encodings/utf_16_be.py*
rm $1/usr/lib/python2.7/encodings/utf_16_le.py*
rm $1/usr/lib/python2.7/encodings/utf_16.py*
rm $1/usr/lib/python2.7/encodings/utf_32_be.py*
rm $1/usr/lib/python2.7/encodings/utf_32_le.py*
rm $1/usr/lib/python2.7/encodings/utf_32.py*
rm $1/usr/lib/python2.7/encodings/utf_7.py*
rm $1/usr/lib/python2.7/encodings/utf_8_sig.py*
rm $1/usr/lib/python2.7/encodings/uu_codec.py*
rm $1/usr/lib/python2.7/encodings/zlib_codec.py*
rm $1/usr/lib/python2.7/filecmp.py*
rm $1/usr/lib/python2.7/fileinput.py*
rm $1/usr/lib/python2.7/fnmatch.py*
rm $1/usr/lib/python2.7/formatter.py*
rm $1/usr/lib/python2.7/fpformat.py*
rm $1/usr/lib/python2.7/fractions.py*
rm $1/usr/lib/python2.7/ftplib.py*
rm $1/usr/lib/python2.7/getopt.py*
rm $1/usr/lib/python2.7/getpass.py*
rm $1/usr/lib/python2.7/glob.py*
rm $1/usr/lib/python2.7/gzip.py*
rm $1/usr/lib/python2.7/hmac.py*
rm $1/usr/lib/python2.7/hotshot/__init__.py*
rm $1/usr/lib/python2.7/hotshot/log.py*
rm $1/usr/lib/python2.7/hotshot/stats.py*
rm $1/usr/lib/python2.7/hotshot/stones.py*
rm $1/usr/lib/python2.7/htmlentitydefs.py*
rm $1/usr/lib/python2.7/ihooks.py*
rm $1/usr/lib/python2.7/imaplib.py*
rm $1/usr/lib/python2.7/imghdr.py*
rm $1/usr/lib/python2.7/importlib/__init__.py*
rm $1/usr/lib/python2.7/imputil.py*
#rm $1/usr/lib/python2.7/inspect.py*
rm $1/usr/lib/python2.7/json/tool.py*
rm $1/usr/lib/python2.7/macpath.py*
rm $1/usr/lib/python2.7/macurl2path.py*
rm $1/usr/lib/python2.7/mailbox.py*
rm $1/usr/lib/python2.7/mailcap.py*
rm $1/usr/lib/python2.7/markupbase.py*
rm $1/usr/lib/python2.7/md5.py*
rm $1/usr/lib/python2.7/mhlib.py*
rm $1/usr/lib/python2.7/mimetypes.py*
rm $1/usr/lib/python2.7/MimeWriter.py*
rm $1/usr/lib/python2.7/mimify.py*
rm $1/usr/lib/python2.7/modulefinder.py*
rm $1/usr/lib/python2.7/multifile.py*
rm $1/usr/lib/python2.7/multiprocessing/__init__.py*
rm $1/usr/lib/python2.7/multiprocessing/connection.py*
rm $1/usr/lib/python2.7/multiprocessing/dummy/__init__.py*
rm $1/usr/lib/python2.7/multiprocessing/dummy/connection.py*
rm $1/usr/lib/python2.7/multiprocessing/forking.py*
rm $1/usr/lib/python2.7/multiprocessing/heap.py*
rm $1/usr/lib/python2.7/multiprocessing/managers.py*
rm $1/usr/lib/python2.7/multiprocessing/pool.py*
rm $1/usr/lib/python2.7/multiprocessing/process.py*
rm $1/usr/lib/python2.7/multiprocessing/queues.py*
rm $1/usr/lib/python2.7/multiprocessing/reduction.py*
rm $1/usr/lib/python2.7/multiprocessing/sharedctypes.py*
rm $1/usr/lib/python2.7/multiprocessing/synchronize.py*
rm $1/usr/lib/python2.7/multiprocessing/util.py*
rm $1/usr/lib/python2.7/mutex.py*
rm $1/usr/lib/python2.7/netrc.py*
rm $1/usr/lib/python2.7/new.py*
rm $1/usr/lib/python2.7/nntplib.py*
rm $1/usr/lib/python2.7/ntpath.py*
rm $1/usr/lib/python2.7/nturl2path.py*
rm $1/usr/lib/python2.7/numbers.py*
#rm $1/usr/lib/python2.7/opcode.py*
rm $1/usr/lib/python2.7/os2emxpath.py*
rm $1/usr/lib/python2.7/pdb.py*
rm $1/usr/lib/python2.7/pickletools.py*
rm $1/usr/lib/python2.7/pipes.py*
rm $1/usr/lib/python2.7/plat-linux2/CDROM.py*
rm $1/usr/lib/python2.7/plat-linux2/IN.py*
rm $1/usr/lib/python2.7/plat-linux2/TYPES.py*
rm $1/usr/lib/python2.7/plistlib.py*
rm $1/usr/lib/python2.7/popen2.py*
rm $1/usr/lib/python2.7/poplib.py*
rm $1/usr/lib/python2.7/posixfile.py*
rm $1/usr/lib/python2.7/pprint.py*
rm $1/usr/lib/python2.7/profile.py*
rm $1/usr/lib/python2.7/pstats.py*
rm $1/usr/lib/python2.7/pty.py*
rm $1/usr/lib/python2.7/py_compile.py*
rm $1/usr/lib/python2.7/pyclbr.py*
rm $1/usr/lib/python2.7/quopri.py*
rm $1/usr/lib/python2.7/repr.py*
rm $1/usr/lib/python2.7/rexec.py*
rm $1/usr/lib/python2.7/rlcompleter.py*
rm $1/usr/lib/python2.7/robotparser.py*
rm $1/usr/lib/python2.7/runpy.py*
rm $1/usr/lib/python2.7/sched.py*
rm $1/usr/lib/python2.7/sets.py*
rm $1/usr/lib/python2.7/sgmllib.py*
rm $1/usr/lib/python2.7/sha.py*
rm $1/usr/lib/python2.7/shelve.py*
rm $1/usr/lib/python2.7/shutil.py*
rm $1/usr/lib/python2.7/SimpleXMLRPCServer.py*
rm $1/usr/lib/python2.7/smtpd.py*
rm $1/usr/lib/python2.7/smtplib.py*
rm $1/usr/lib/python2.7/sndhdr.py*
rm $1/usr/lib/python2.7/sre.py*
rm $1/usr/lib/python2.7/statvfs.py*
rm $1/usr/lib/python2.7/StringIO.py*
rm $1/usr/lib/python2.7/stringold.py*
#rm $1/usr/lib/python2.7/stringprep.py*
rm $1/usr/lib/python2.7/sunau.py*
rm $1/usr/lib/python2.7/sunaudio.py*
rm $1/usr/lib/python2.7/symbol.py*
rm $1/usr/lib/python2.7/symtable.py*
rm $1/usr/lib/python2.7/tabnanny.py*
rm $1/usr/lib/python2.7/tarfile.py*
rm $1/usr/lib/python2.7/telnetlib.py*
rm $1/usr/lib/python2.7/this.py*
rm $1/usr/lib/python2.7/timeit.py*
rm $1/usr/lib/python2.7/toaiff.py*
#rm $1/usr/lib/python2.7/token.py*
#rm $1/usr/lib/python2.7/tokenize.py*
rm $1/usr/lib/python2.7/trace.py*
rm $1/usr/lib/python2.7/tty.py*
rm $1/usr/lib/python2.7/unittest/__init__.py*
rm $1/usr/lib/python2.7/unittest/__main__.py*
rm $1/usr/lib/python2.7/unittest/case.py*
rm $1/usr/lib/python2.7/unittest/loader.py*
rm $1/usr/lib/python2.7/unittest/main.py*
rm $1/usr/lib/python2.7/unittest/result.py*
rm $1/usr/lib/python2.7/unittest/runner.py*
rm $1/usr/lib/python2.7/unittest/signals.py*
rm $1/usr/lib/python2.7/unittest/suite.py*
rm $1/usr/lib/python2.7/unittest/test/__init__.py*
rm $1/usr/lib/python2.7/unittest/test/dummy.py*
rm $1/usr/lib/python2.7/unittest/test/support.py*
rm $1/usr/lib/python2.7/unittest/test/test_assertions.py*
rm $1/usr/lib/python2.7/unittest/test/test_break.py*
rm $1/usr/lib/python2.7/unittest/test/test_case.py*
rm $1/usr/lib/python2.7/unittest/test/test_discovery.py*
rm $1/usr/lib/python2.7/unittest/test/test_functiontestcase.py*
rm $1/usr/lib/python2.7/unittest/test/test_loader.py*
rm $1/usr/lib/python2.7/unittest/test/test_program.py*
rm $1/usr/lib/python2.7/unittest/test/test_result.py*
rm $1/usr/lib/python2.7/unittest/test/test_runner.py*
rm $1/usr/lib/python2.7/unittest/test/test_setups.py*
rm $1/usr/lib/python2.7/unittest/test/test_skipping.py*
rm $1/usr/lib/python2.7/unittest/test/test_suite.py*
rm $1/usr/lib/python2.7/unittest/util.py*
rm $1/usr/lib/python2.7/user.py*
rm $1/usr/lib/python2.7/UserList.py*
rm $1/usr/lib/python2.7/UserString.py*
rm $1/usr/lib/python2.7/uu.py*
rm $1/usr/lib/python2.7/wave.py*
rm $1/usr/lib/python2.7/webbrowser.py*
rm $1/usr/lib/python2.7/whichdb.py*
rm $1/usr/lib/python2.7/wsgiref/__init__.py*
rm $1/usr/lib/python2.7/wsgiref/handlers.py*
rm $1/usr/lib/python2.7/wsgiref/headers.py*
rm $1/usr/lib/python2.7/wsgiref/simple_server.py*
rm $1/usr/lib/python2.7/wsgiref/util.py*
rm $1/usr/lib/python2.7/wsgiref/validate.py*
rm $1/usr/lib/python2.7/xdrlib.py*
#rm $1/usr/lib/python2.7/xml/__init__.py*
rm $1/usr/lib/python2.7/xml/dom/__init__.py*
rm $1/usr/lib/python2.7/xml/dom/domreg.py*
rm $1/usr/lib/python2.7/xml/dom/minicompat.py*
rm $1/usr/lib/python2.7/xml/dom/minidom.py*
rm $1/usr/lib/python2.7/xml/dom/NodeFilter.py*
rm $1/usr/lib/python2.7/xml/dom/pulldom.py*
rm $1/usr/lib/python2.7/xml/dom/xmlbuilder.py*
#rm $1/usr/lib/python2.7/xml/etree/__init__.py*
#rm $1/usr/lib/python2.7/xml/etree/cElementTree.py*
#rm $1/usr/lib/python2.7/xml/etree/ElementInclude.py*
#rm $1/usr/lib/python2.7/xml/etree/ElementPath.py*
#rm $1/usr/lib/python2.7/xml/etree/ElementTree.py*
#rm $1/usr/lib/python2.7/xml/parsers/__init__.py*
#rm $1/usr/lib/python2.7/xml/parsers/expat.py*
rm $1/usr/lib/python2.7/xml/sax/__init__.py*
rm $1/usr/lib/python2.7/xml/sax/_exceptions.py*
rm $1/usr/lib/python2.7/xml/sax/expatreader.py*
rm $1/usr/lib/python2.7/xml/sax/handler.py*
rm $1/usr/lib/python2.7/xml/sax/saxutils.py*
rm $1/usr/lib/python2.7/xml/sax/xmlreader.py*
rm $1/usr/lib/python2.7/xmllib.py*
rm $1/usr/lib/python2.7/xmlrpclib.py*
rm $1/usr/lib/python2.7/zipfile.py*
rm $1/usr/lib/python2.7/lib-dynload/cmath.so
#rm $1/usr/lib/python2.7/lib-dynload/_ctypes.so
rm $1/usr/lib/python2.7/lib-dynload/future_builtins.so
rm $1/usr/lib/python2.7/lib-dynload/syslog.so
rm $1/usr/lib/python2.7/lib-dynload/_multibytecodec.so
rm $1/usr/lib/python2.7/lib-dynload/spwd.so
rm $1/usr/lib/python2.7/lib-dynload/termios.so
rm $1/usr/lib/python2.7/lib-dynload/_hotshot.so
rm $1/usr/lib/python2.7/_locale.so
rm $1/usr/lib/python2.7/lib-dynload/lib-dynload/_multiprocessing.so
rm $1/usr/lib/python2.7/lib-dynload/_elementtree.so
rm $1/usr/lib/python2.7/lib-dynload/ossaudiodev.so
rm $1/usr/lib/python2.7/lib-dynload/strop.so
rm $1/usr/lib/python2.7/lib-dynload/crypt.so
rm $1/usr/lib/python2.7/lib-dynload/parser.so
rm $1/usr/lib/python2.7/lib-dynload/_codecs_cn.so
rm $1/usr/lib/python2.7/lib-dynload/linuxaudiodev.so
rm $1/usr/lib/python2.7/lib-dynload/_codecs_hk.so
rm $1/usr/lib/python2.7/lib-dynload/_codecs_jp.so
rm $1/usr/lib/python2.7/lib-dynload/_codecs_kr.so
rm $1/usr/lib/python2.7/lib-dynload/_codecs_tw.so
rm $1/usr/lib/python2.7/lib-dynload/resource.so
rm $1/usr/lib/python2.7/lib-dynload/_csv.so
rm $1/usr/lib/python2.7/lib-dynload/_heapq.so
rm $1/usr/lib/python2.7/lib-dynload/_lsprof.so
rm $1/usr/lib/python2.7/lib-dynload/_json.so
rm $1/usr/lib/python2.7/lib-dynload/mmap.so
rm $1/usr/lib/python2.7/lib-dynload/grp.so
rm $1/usr/lib/python2.7/lib-dynload/_bisect.so
rm $1/usr/lib/python2.7/lib-dynload/_codecs_iso2022.so
rm $1/usr/lib/python2.7/lib-dynload/audioop.so
